include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_return_types_on_setters: true
    avoid_types_as_parameter_names: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    close_sinks: true
    constant_identifier_names: true
    control_flow_in_finally_blocks: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    hash_and_equals: true
    no_duplicate_case_values: true
    no_leading_underscores_for_local_identifiers: true
    null_check_on_nullable_type_parameter: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_null_aware_operators: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: true
    recursive_getters: true
    slash_for_doc_comments: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_key_in_widget_constructors: true
    valid_regexps: true
